# Use official Node.js image as the base image
FROM node:18-alpine

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json (if exists)
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code into the container
COPY . ./

# Install dotenv package to load environment variables from .env file
RUN npm install dotenv

# Expose the port your Express app runs on (default is 5000)
EXPOSE 8000

# Run the application
CMD ["npm", "run", "dev"]
