name: Deploy ExpressJs backend

on:
 push:
  branches:
   - Development

jobs:
 build:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Login to docker hub
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
    - name: Build Docker Image
      run: docker build -t charitha124/express-js:latest .
    - name: Publish Image to docker hub
      run: docker push charitha124/express-js:latest


 deploy:
  needs: build
  runs-on: self-hosted
  steps:
   - name: Pull image from docker hub
     run: docker pull charitha124/express-js:latest
   - name: Run docker container
     run: docker run -d -p 8000:8000 --name express-js-container charitha124/express-js:latest